// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RestaurantPOS.Models;
using System;

namespace RestaurantPOS.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180510073638_Orders")]
    partial class Orders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestaurantPOS.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ClosedDate");

                    b.Property<decimal>("Discount");

                    b.Property<DateTime>("OpenedDate");

                    b.Property<int>("State");

                    b.Property<decimal>("Tips");

                    b.Property<string>("Waiter");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("RestaurantPOS.Models.OrderInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("OrderId");

                    b.Property<Guid>("TableId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("RestaurantPOS.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("CustomerMedia");

                    b.Property<string>("Name");

                    b.Property<Guid?>("OrderId");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("RestaurantPOS.Models.SeatNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Number");

                    b.Property<Guid?>("OrderInfoId");

                    b.HasKey("Id");

                    b.HasIndex("OrderInfoId");

                    b.ToTable("SeatNumber");
                });

            modelBuilder.Entity("RestaurantPOS.Models.OrderInfo", b =>
                {
                    b.HasOne("RestaurantPOS.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("RestaurantPOS.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantPOS.Models.Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("RestaurantPOS.Models.SeatNumber", b =>
                {
                    b.HasOne("RestaurantPOS.Models.OrderInfo")
                        .WithMany("TableSeatsNumbers")
                        .HasForeignKey("OrderInfoId");
                });
#pragma warning restore 612, 618
        }
    }
}
